/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Articulo.java
 *
 * Created on 22/08/2008, 07:40:21 PM
 */

package omoikane.formularios;

import javax.swing.*;
import java.awt.*;
import java.awt.image.*;
import omoikane.sistema.*;

/**
 *
 * @author Octavio
 */
public class Articulo extends javax.swing.JInternalFrame {

    BufferedImage fondo;
    public int ID;
    /** Creates new form Articulo */
    public Articulo() {
        initComponents();
        //Instrucciones para el funcionamiento del fondo semistransparente
        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDArticulo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtImpuestos = new javax.swing.JTextField();
        txtUModificacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtIDLinea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtExistencias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUtilidad = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();

        setTitle("Artículos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Artículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 80, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Artículo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        txtIDArticulo.setEditable(false);
        getContentPane().add(txtIDArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 260, -1));

        txtCodigo.setEditable(false);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 260, -1));

        txtDescripcion.setEditable(false);
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 260, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Impuestos (%):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>Última<br>Modificación:</html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtImpuestos.setEditable(false);
        getContentPane().add(txtImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 260, -1));

        txtUModificacion.setEditable(false);
        getContentPane().add(txtUModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 30));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 80, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Línea:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        txtIDLinea.setEditable(false);
        txtIDLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDLineaActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Costo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        txtCosto.setEditable(false);
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 260, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Existencias:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        txtExistencias.setEditable(false);
        getContentPane().add(txtExistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Utilidad (%):");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        txtUtilidad.setEditable(false);
        getContentPane().add(txtUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 260, -1));

        txtDescuento.setEditable(false);
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 260, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descuento (%):");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        txtUnidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pza", "Kg", "Lt" }));
        txtUnidad.setEnabled(false);
        getContentPane().add(txtUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 260, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        omoikane.principal.Articulos.guardar(this);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        omoikane.principal.Articulos.modificar(this);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtIDLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDLineaActionPerformed

    public void setEditable(boolean editable)
    {
        this.txtCodigo.setEditable(editable);
        this.txtIDLinea.setEditable(editable);
        this.txtDescripcion.setEditable(editable);
        this.txtImpuestos.setEditable(editable);
        this.txtUnidad.setEnabled(editable);
        this.txtCosto.setEditable(editable);
        this.txtUtilidad.setEditable(editable);
        this.txtDescuento.setEditable(editable);
    }
    public void setModoDetalles()
    {
        setEditable(false);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(false);

    }
    public void setModoModificar()
    {
        setEditable(true);
        this.btnGuardar.setVisible(false);
    }
    public void setModoNuevo()
    {
        setEditable(true);
        this.txtExistencias.setEditable(true);
        this.btnModificar.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtExistencias;
    private javax.swing.JTextField txtIDArticulo;
    public javax.swing.JTextField txtIDLinea;
    private javax.swing.JTextField txtImpuestos;
    private javax.swing.JTextField txtUModificacion;
    private javax.swing.JComboBox txtUnidad;
    private javax.swing.JTextField txtUtilidad;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtCodigo
     */
    public String getTxtCodigo() {
        return txtCodigo.getText();
    }

    /**
     * @param txtCodigo the txtCodigo to set
     */
    public void setTxtCodigo(String txtCodigo) {
        this.txtCodigo.setText(txtCodigo);
    }
    public Component getIDLinea() { return this.txtIDLinea; }

    /**
     * @return the txtDescripcion
     */
    public String getTxtDescripcion() {
        return txtDescripcion.getText();
    }

    /**
     * @param txtDescripcion the txtDescripcion to set
     */
    public void setTxtDescripcion(String txtDescripcion) {
        this.txtDescripcion.setText(txtDescripcion);
    }

    /**
     * @return the txtIDArticulo
     */
    public String getTxtIDArticulo() {
        return txtIDArticulo.getText();
    }

    /**
     * @param txtIDArticulo the txtIDArticulo to set
     */
    public void setTxtIDArticulo(String txtIDArticulo) {
        this.txtIDArticulo.setText(txtIDArticulo);
    }

    public String getTxtUnidad()
    {
        return String.valueOf(txtUnidad.getSelectedItem());
    }

    public void setTxtUnidad(String txt)
    {
        this.txtUnidad.setSelectedItem(txt);
    }

    public String getTxtImpuestos()
    {
        return this.txtImpuestos.getText();
    }

    public void setTxtImpuestos(String txt)
    {
        this.txtImpuestos.setText(txt);
    }

    public String getTxtUModificacion()
    {
        return this.txtUModificacion.getText();
    }

    public void setTxtUModificacion(String txt)
    {
        txtUModificacion.setText(txt);
    }

    public String getTxtIDLinea()
    {
        return txtIDLinea.getText();
    }

    public void setTxtIDLinea(String IDLinea)
    {

        txtIDLinea.setText(IDLinea);
    }

    public JTextField getCampoID() {
        return txtIDLinea;
    }

    public String getTxtDescuento()   { return this.txtDescuento.getText(); }
    public String getTxtCosto()       { return this.txtCosto.getText(); }
    public String getTxtUtilidad()    { return this.txtUtilidad.getText(); }
    public String getTxtExistencias() { return this.txtExistencias.getText(); }

    public void setTxtDescuento(String descuento)     { txtDescuento.setText(descuento); }
    public void setTxtCosto(String costo)             { txtCosto.setText(costo); }
    public void setTxtUtilidad(String utilidad)       { txtUtilidad.setText(utilidad); }
    public void setTxtExistencias(String existencias) { txtExistencias.setText(existencias); }
    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }
    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(55,55,255,225));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;
    }
}