/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CorteSucursalDetalles.java
 *
 * Created on 28/02/2009, 09:04:31 PM
 */

package omoikane.formularios;

import javax.swing.*;
import java.awt.*;
import java.awt.image.*;
import omoikane.sistema.*;
/**
 *
 * @author Usuario
 */
public class CorteMovimientoDetalles extends javax.swing.JInternalFrame {

    BufferedImage fondo;
    /** Creates new form CorteSucursalDetalles */
    public CorteMovimientoDetalles() {
        initComponents();
        //Instrucciones para el funcionamiento del fondo semistransparente
        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRetiros = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDepositos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtImpuestos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDescuentos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVentas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNVentas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setTitle("Movimientos de Caja");

        btnAceptar.setText("Aceptar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Importe:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");

        txtRetiros.setFont(new java.awt.Font("Tahoma", 1, 18));
        txtRetiros.setForeground(new java.awt.Color(255, 255, 255));
        txtRetiros.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Autorizado:");

        txtDepositos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDepositos.setForeground(new java.awt.Color(255, 255, 255));
        txtDepositos.setText("0.00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Almacen:");

        txtImpuestos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtImpuestos.setForeground(new java.awt.Color(255, 255, 255));
        txtImpuestos.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cajero:");

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        txtSubtotal.setText("0.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Caja:");

        txtDescuentos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDescuentos.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuentos.setText("0.00");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Id de movimiento :");

        txtVentas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtVentas.setForeground(new java.awt.Color(255, 255, 255));
        txtVentas.setText("0.00");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Movimientos de Caja");

        txtNVentas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNVentas.setForeground(new java.awt.Color(255, 255, 255));
        txtNVentas.setText("0");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo de movimiento :");

        btnImprimir.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addComponent(jLabel15)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImpuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(txtDescuentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDepositos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVentas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtImpuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDepositos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRetiros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnImprimir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel txtDepositos;
    public javax.swing.JLabel txtDescuentos;
    public javax.swing.JLabel txtImpuestos;
    public javax.swing.JLabel txtNVentas;
    public javax.swing.JLabel txtRetiros;
    public javax.swing.JLabel txtSubtotal;
    public javax.swing.JLabel txtTotal;
    public javax.swing.JLabel txtVentas;
    // End of variables declaration//GEN-END:variables

    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }
    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(55,55,255,225));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;
    }

    /**
     * @return the btnAceptar
     */
    public javax.swing.JButton getBtnAceptar() {
        return btnAceptar;
    }

    /**
     * @param btnAceptar the btnAceptar to set
     */
    public void setBtnAceptar(javax.swing.JButton btnAceptar) {
        this.btnAceptar = btnAceptar;
    }

    /**
     * @return the txtDescuentos
     */
    public javax.swing.JLabel getTxtDescuentos() {
        return txtDescuentos;
    }

    /**
     * @param txtDescuentos the txtDescuentos to set
     */
    public void setTxtDescuentos(javax.swing.JLabel txtDescuentos) {
        this.txtDescuentos = txtDescuentos;
    }

    /**
     * @return the txtImpuestos
     */
    public javax.swing.JLabel getTxtImpuestos() {
        return txtImpuestos;
    }

    /**
     * @param txtImpuestos the txtImpuestos to set
     */
    public void setTxtImpuestos(javax.swing.JLabel txtImpuestos) {
        this.txtImpuestos = txtImpuestos;
    }

    /**
     * @return the txtDepositos
     */
    public javax.swing.JLabel getTxtDepositos() {
        return txtDepositos;
    }

    /**
     * @param txtIngresos the txtDepositos to set
     */
    public void setTxtDepositos(javax.swing.JLabel txtIngresos) {
        this.txtDepositos = txtIngresos;
    }

    /**
     * @return the txtRetiros
     */
    public javax.swing.JLabel getTxtRetiros() {
        return txtRetiros;
    }

    /**
     * @param txtRetiros the txtRetiros to set
     */
    public void setTxtRetiros(javax.swing.JLabel txtRetiros) {
        this.txtRetiros = txtRetiros;
    }

    /**
     * @return the txtSubtotal
     */
    public javax.swing.JLabel getTxtSubtotal() {
        return txtSubtotal;
    }

    /**
     * @param txtSubtotal the txtSubtotal to set
     */
    public void setTxtSubtotal(javax.swing.JLabel txtSubtotal) {
        this.txtSubtotal = txtSubtotal;
    }

    /**
     * @return the txtTotal
     */
    public javax.swing.JLabel getTxtTotal() {
        return txtTotal;
    }

    /**
     * @param txtTotal the txtTotal to set
     */
    public void setTxtTotal(javax.swing.JLabel txtTotal) {
        this.txtTotal = txtTotal;
    }

    /**
     * @return the txtVentas
     */
    public javax.swing.JLabel getTxtVentas() {
        return txtVentas;
    }

    /**
     * @param txtVentas the txtVentas to set
     */
    public void setTxtVentas(javax.swing.JLabel txtVentas) {
        this.txtVentas = txtVentas;
    }

    /**
     * @return the txtNVentas
     */
    public javax.swing.JLabel getTxtNVentas() {
        return txtNVentas;
    }

    /**
     * @param txtNVentas the txtNVentas to set
     */
    public void setTxtNVentas(javax.swing.JLabel txtNVentas) {
        this.txtNVentas = txtNVentas;
    }
}
