/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Articulo.java
 *
 * Created on 22/08/2008, 07:40:21 PM
 */

package omoikane.formularios;

import javax.swing.*;
import java.awt.*;
import java.awt.image.*;
import omoikane.sistema.*;

/**
 *
 * @author Octavio
 */
public class CorteCajaDetalles extends javax.swing.JInternalFrame {

    BufferedImage fondo;
    public int ID;
    /** Creates new form Articulo */
    public CorteCajaDetalles() {
        initComponents();
        //Instrucciones para el funcionamiento del fondo semistransparente
        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);

        Herramientas.centrarVentana(this);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDCorte = new javax.swing.JTextField();
        txtIDCaja = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtImpuestos = new javax.swing.JTextField();
        txtUModificacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIDAlmacen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtExistencias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUtilidad = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtImpuestos1 = new javax.swing.JTextField();

        setTitle("Corte de Caja");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Corte de Caja");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 80, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Corte:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Caja:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Creacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        txtIDCorte.setEditable(false);
        getContentPane().add(txtIDCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 260, -1));

        txtIDCaja.setEditable(false);
        getContentPane().add(txtIDCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 260, -1));

        txtFecha.setEditable(false);
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 260, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de Ventas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subtotal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hasta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtImpuestos.setEditable(false);
        getContentPane().add(txtImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 260, -1));

        txtUModificacion.setEditable(false);
        getContentPane().add(txtUModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 260, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Almacen:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        txtIDAlmacen.setEditable(false);
        txtIDAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDAlmacenActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Impuesto:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        txtCosto.setEditable(false);
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 260, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        txtExistencias.setEditable(false);
        getContentPane().add(txtExistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 260, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descuento:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        txtUtilidad.setEditable(false);
        getContentPane().add(txtUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 260, -1));

        txtDescuento.setEditable(false);
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 260, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Desde:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 10, 10));

        txtImpuestos1.setEditable(false);
        getContentPane().add(txtImpuestos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btnCerrarActionPerformed

    private void txtIDAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDAlmacenActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtIDAlmacenActionPerformed

    public void setEditable(boolean editable)
    {
        this.txtIDCaja.setEditable(editable);
        this.txtIDAlmacen.setEditable(editable);
        this.txtFecha.setEditable(editable);
        this.txtImpuestos.setEditable(editable);
        this.txtUnidad.setEnabled(editable);
        this.txtCosto.setEditable(editable);
        this.txtUtilidad.setEditable(editable);
        this.txtDescuento.setEditable(editable);
    }
    public void setModoDetalles()
    {
        setEditable(false);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(false);

    }
    public void setModoModificar()
    {
        setEditable(true);
        this.btnGuardar.setVisible(false);
        this.btnModificar.setVisible(true);
    }
    public void setModoNuevo()
    {
        setEditable(true);
        this.txtExistencias.setEditable(true);
        this.btnModificar.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtExistencias;
    private javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtIDAlmacen;
    private javax.swing.JTextField txtIDCaja;
    private javax.swing.JTextField txtIDCorte;
    private javax.swing.JTextField txtImpuestos;
    private javax.swing.JTextField txtImpuestos1;
    private javax.swing.JTextField txtUModificacion;
    private javax.swing.JTextField txtUtilidad;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtCodigo
     */
    public String getTxtCodigo() {
        return txtIDCaja.getText();
    }

    /**
     * @param txtCodigo the txtCodigo to set
     */
    public void setTxtCodigo(String txtCodigo) {
        this.txtIDCaja.setText(txtCodigo);
    }
    public Component getIDLinea() { return this.txtIDAlmacen; }

    /**
     * @return the txtDescripcion
     */
    public String getTxtDescripcion() {
        return txtFecha.getText();
    }

    /**
     * @param txtDescripcion the txtDescripcion to set
     */
    public void setTxtDescripcion(String txtDescripcion) {
        this.txtFecha.setText(txtDescripcion);
    }

    /**
     * @return the txtIDArticulo
     */
    public String getTxtIDArticulo() {
        return txtIDCorte.getText();
    }

    /**
     * @param txtIDArticulo the txtIDArticulo to set
     */
    public void setTxtIDArticulo(String txtIDArticulo) {
        this.txtIDCorte.setText(txtIDArticulo);
    }

    public String getTxtUnidad()
    {
        return String.valueOf(txtUnidad.getSelectedItem());
    }

    public void setTxtUnidad(String txt)
    {
        this.txtUnidad.setSelectedItem(txt);
    }

    public String getTxtImpuestos()
    {
        return this.txtImpuestos.getText();
    }

    public void setTxtImpuestos(String txt)
    {
        this.txtImpuestos.setText(txt);
    }

    public String getTxtUModificacion()
    {
        return this.txtUModificacion.getText();
    }

    public void setTxtUModificacion(String txt)
    {
        txtUModificacion.setText(txt);
    }

    public String getTxtIDLinea()
    {
        return txtIDAlmacen.getText();
    }

    public void setTxtIDLinea(String IDLinea)
    {

        txtIDAlmacen.setText(IDLinea);
    }

    public JTextField getCampoID() {
        return txtIDAlmacen;
    }

    public String getTxtDescuento()   { return this.txtDescuento.getText(); }
    public String getTxtCosto()       { return this.txtCosto.getText(); }
    public String getTxtUtilidad()    { return this.txtUtilidad.getText(); }
    public String getTxtExistencias() { return this.txtExistencias.getText(); }

    public void setTxtDescuento(String descuento)     { txtDescuento.setText(descuento); }
    public void setTxtCosto(String costo)             { txtCosto.setText(costo); }
    public void setTxtUtilidad(String utilidad)       { txtUtilidad.setText(utilidad); }
    public void setTxtExistencias(String existencias) { txtExistencias.setText(existencias); }
    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }
    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(55,55,255,225));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;
    }
}