/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListadoFacturas.java
 *
 * Created on 23/10/2009, 09:31:20 AM
 */
package omoikane.formularios;

import java.util.*;
import java.awt.event.*;
import java.awt.image.*;
import java.awt.*;
import javax.swing.table.*;
import javax.swing.*;
import javax.swing.event.*;
import omoikane.sistema.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;
import omoikane.sistema.Herramientas;
import javax.swing.JOptionPane;
import java.text.*;

/**
 *
 * @author Phesus - RNB
 */
public class ListadoFacturas extends javax.swing.JInternalFrame {

    public boolean modal = false;
    public int IDAlmacen = omoikane.principal.Principal.IDAlmacen;
    BufferedImage          fondo;
    public int             IDSeleccionado;
    public String          codigoSeleccionado;
    public String          txtQuery;

    /** Creates new form ListadoFacturas */
    public ListadoFacturas() {
        initComponents();
        this.setOpaque(false);
        ((JPanel)this.getContentPane()).setOpaque(false);
        this.getLayeredPane().setOpaque(false);
        this.getRootPane().setOpaque(false);
        this.generarFondo(this);
        // this.txtFecha.setDate(new java.util.Date());
        Herramientas.centrarVentana(this);
        Calendar calendario = Calendar.getInstance();
        this.dateHasta.setDate(calendario.getTime());
        calendario.add(Calendar.DAY_OF_MONTH, -15);
        this.dateDesde.setDate(calendario.getTime());
    }

    @Override
    public void paintComponent(Graphics g)
    {
      Graphics2D g2d = (Graphics2D) g;
      g2d.drawImage(fondo, 0, 0, null);

    }
    public void generarFondo(Component componente)
    {
      Rectangle areaDibujo = this.getBounds();
      BufferedImage tmp;
      GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();

      tmp = gc.createCompatibleImage(areaDibujo.width, areaDibujo.height,BufferedImage.TRANSLUCENT);
      Graphics2D g2d = (Graphics2D) tmp.getGraphics();
      g2d.setColor(new Color(55,55,255,165));
      g2d.fillRect(0,0,areaDibujo.width,areaDibujo.height);
      fondo = tmp;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnDetalles = new javax.swing.JButton();
        btnNueva = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        dateDesde = new org.jdesktop.swingx.JXDatePicker();
        dateHasta = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Facturación");

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/64x64/back.png"))); // NOI18N
        btnCerrar.setText("<HTML>Regresar a menú [Esc]</HTML>");
        btnCerrar.setFocusable(false);
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar [F3]:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/32x32/page_search.png"))); // NOI18N
        btnDetalles.setText("Detalles [F4]");
        btnDetalles.setFocusable(false);
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });

        btnNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/32x32/page_add.png"))); // NOI18N
        btnNueva.setText("Nueva [F5]");
        btnNueva.setFocusable(false);
        btnNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/32x32/page_remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar [Supr]");
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Factura", "Cancelada", "Ventas", "Total"
            }
        ));
        tblFacturas.setFocusable(false);
        jScrollPane1.setViewportView(tblFacturas);

        jButton1.setText("Busqueda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetalles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNueva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(48, 48, 48)
                        .addComponent(dateDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalles)
                    .addComponent(btnNueva)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        // VentasTableModel tabModelo = this.modelo;
        // this.modelo = null;
        // tabModelo.destroy();
        this.dispose();
        if (!modal) {
            ((javax.swing.JInternalFrame)((omoikane.principal.MenuPrincipal)omoikane.principal.Principal.getMenuPrincipal()).getMenuPrincipal()).requestFocusInWindow();
        }
}//GEN-LAST:event_btnCerrarActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:
       
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            this.txtBusqueda.selectAll();
        }
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN) {
            int sigFila = tblFacturas.getSelectedRow()+1;
            if(sigFila < tblFacturas.getRowCount()) {
                this.tblFacturas.setRowSelectionInterval(sigFila, sigFila);
                this.tblFacturas.scrollRectToVisible(tblFacturas.getCellRect(sigFila, 1, true));
            }
        }
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP) {
            int antFila = tblFacturas.getSelectedRow()-1;
            if(antFila >= 0) {
                this.tblFacturas.setRowSelectionInterval(antFila, antFila);
                this.tblFacturas.scrollRectToVisible(tblFacturas.getCellRect(antFila, 1, true));
            }
        }
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_PAGE_DOWN) {
            int nFilas  = (int) this.jScrollPane1.getViewportBorderBounds().getHeight() / tblFacturas.getRowHeight();
            int sigFila = tblFacturas.getSelectedRow()+nFilas;
            if(sigFila > tblFacturas.getRowCount()) {
                sigFila = tblFacturas.getRowCount()-1;
            }
            if(sigFila < tblFacturas.getRowCount()) {
                this.tblFacturas.setRowSelectionInterval(sigFila, sigFila);
                this.tblFacturas.scrollRectToVisible(tblFacturas.getCellRect(sigFila, 1, true));
            }
        }
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_PAGE_UP) {
            int nFilas  = (int) this.jScrollPane1.getViewportBorderBounds().getHeight() / tblFacturas.getRowHeight();
            int antFila = tblFacturas.getSelectedRow()-nFilas;
            if(antFila < 0) {
                antFila = 0;
            }
            this.tblFacturas.setRowSelectionInterval(antFila, antFila);
            this.tblFacturas.scrollRectToVisible(tblFacturas.getCellRect(antFila, 1, true));
        }
        /*
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) {
            btnCerrar.doClick();
        }
        */
}//GEN-LAST:event_txtBusquedaKeyPressed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        JInternalFrame wnd = (JInternalFrame) omoikane.principal.Facturas.lanzarFacturaDetalles(this);
        wnd.addInternalFrameListener(iframeAdapter);
}//GEN-LAST:event_btnDetallesActionPerformed

    private void btnNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaActionPerformed
      JInternalFrame wnd = (JInternalFrame) omoikane.principal.Facturas.lanzarFacturaNueva();
        wnd.addInternalFrameListener(iframeAdapter);
}//GEN-LAST:event_btnNuevaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "¿Realmente desea cancelar esta factura : ?", "seguro...", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
        omoikane.principal.Facturas.cancelarFacturaDesdeLista(this);
        reset();
       }
}//GEN-LAST:event_btnCancelarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE)
            btnCerrar.doClick();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F4)
            btnDetalles.doClick();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_F5)
            btnNueva.doClick();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DELETE)
            btnCancelar.doClick();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnNueva;
    private org.jdesktop.swingx.JXDatePicker dateDesde;
    private org.jdesktop.swingx.JXDatePicker dateHasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFacturas;
    public javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables



    public void reset()
    {
        String[] columnas = {"Fecha", "Factura","Cancelada","Ventas","Total"};
        this.tblFacturas.setModel(new DefaultTableModel());
        ((DefaultTableModel)this.tblFacturas.getModel()).setColumnIdentifiers(columnas);
        omoikane.principal.Facturas.poblarListadoFacturas(this);
        this.txtBusqueda.requestFocus();

    }

    public String getBusqueda(){
        String resultado = "";
                resultado = this.txtBusqueda.getText();
                return resultado;

    }

    public String getFechaDesde(){
        String fechaDesde     = "";
        SimpleDateFormat sdf  = new SimpleDateFormat("yyyy-MM-dd");
        if(this.dateDesde.getDate() != null)
        {
            try {
                fechaDesde = sdf.format(this.dateDesde.getDate());
            } catch(Exception e) { JOptionPane.showMessageDialog(null, "Error en el registro: Fecha invalida"); }
        }
        fechaDesde= "'"+fechaDesde+"'";
        return fechaDesde ;

    }

    public String getFechaHasta(){
        String fechaHasta     = "";
        SimpleDateFormat sdf  = new SimpleDateFormat("yyyy-MM-dd");
        if(this.dateHasta.getDate() != null)
        {
            try {
                fechaHasta = sdf.format(this.dateHasta.getDate());
            } catch(Exception e) { JOptionPane.showMessageDialog(null, "Error en el registro: Fecha invalida"); }
        }
        fechaHasta= "'"+fechaHasta+"'";
        return fechaHasta ;
    }

    public InternalFrameAdapter iframeAdapter = new InternalFrameAdapter()
    {public void internalFrameClosed(InternalFrameEvent e) { reset(); }};
}
