/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CodigoArticulo.java
 *
 * Created on 5/04/2009, 06:25:10 PM
 */

package omoikane.formularios;

import java.awt.image.BufferedImage;
import java.awt.*;

/**
 *
 * @author SYSTEM
 */
public class Reporte extends javax.swing.JInternalFrame {

    public BufferedImage fondo;
    /** Creates new form CodigoArticulo */
    public Reporte() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();

        setTitle("Reporte");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Panel.setLayout(new javax.swing.BoxLayout(Panel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(Panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void paintComponent(java.awt.Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(fondo, 0, 0, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    // End of variables declaration//GEN-END:variables

}
